import { useState } from "react";
import { v4 as uuidv4 } from "uuid";

//types
import { type Student } from "../types/student-types.ts";

//components
import ButtonComp from "../components/ButtonComp.tsx";
import SingleInputComp from "../components/SingleInputComp.tsx";

//this defines the type of any props passed in to the addStudentForm component. void is used to state that nothing is expected to be returned.
type AddStudentFormProps = {
    heading: string;
    addStudent: (student: Student) => void;
}

//this defines the addStudent prop and declares it as type 'AddStudentFormProps'
const AddStudentForm = ({heading, addStudent} : AddStudentFormProps) => {
    //the state for all properties in formData is inferred
    const [formData, setFormData] = useState({
        firstName: "",
        lastName: "",
        email: ""
    });

    //this defines the event 'e' as a change event generated by a HTML input, because of this the properties associated with the input are accessible (e.g. target) and therefore the types of name and value can be found.
    const handleInputChanges = (e: React.ChangeEvent<HTMLInputElement>) => {
        const {name, value} = e.target;

        setFormData((prevFormData) => {
            return {
                ...prevFormData,
                [name]: value //uses computed property names 
            }
        });
    }

    //this defines the event 'e' as a form submission event coming from a form element, because of this the preventDefault method is is accessible.
    const handleSubmitStudentForm = (e: React.SubmitEvent<HTMLFormElement>) => {
        e.preventDefault();

        //collect form data values and submit as the addStudent function's argument
        addStudent({
            id: uuidv4(),
            firstName: formData.firstName,
            lastName: formData.lastName,
            email: formData.email
        });

        //reset form data fields
        setFormData({
            firstName: '',
            lastName: '',
            email: ''
        });
    }

    return (
        <section className="studentFormModule">
            <div className="container">
                <div className="grid">
                    <div className="col-4 sm-col-12 lg-start-4 lg-col-6">
                        <form action="" onSubmit={handleSubmitStudentForm}>
                            <div className="h3 center studentFormModule__heading">{heading}</div>
                            <div className="input__wrapper">
                                <SingleInputComp 
                                    label="First name"
                                    labelId="firstName"
                                    type="text"
                                    placeholder="e.g. John"
                                    name="firstName"
                                    value={formData.firstName}
                                    onChange={handleInputChanges}
                                    required
                                />
                            </div>
                            <div className="input__wrapper">
                                <SingleInputComp 
                                    label="Last name"
                                    labelId="lastName"
                                    type="text"
                                    placeholder="e.g. Doe"
                                    name="lastName"
                                    value={formData.lastName}
                                    onChange={handleInputChanges}
                                    required
                                />
                            </div>
                            <div className="input__wrapper">
                                <SingleInputComp 
                                    label="Email"
                                    labelId="email"
                                    type="text"
                                    placeholder="e.g. JohnDoe@gmail.com"
                                    name="email"
                                    value={formData.email}
                                    onChange={handleInputChanges}
                                    required
                                />
                            </div>
                            <ButtonComp type="submit" variant="primary" title="Submit" />
                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default AddStudentForm;