import { useState } from "react";
import { v4 as uuidv4 } from "uuid";

//types
import { type Student } from "../types/student-types.ts";

//this defines the type of any props passed in to the addStudentForm component. void is used to state that nothing is expected to be returned.
type AddStudentFormProps = {
    addStudent: (student: Student) => void;
}

//this defines the addStudent prop and declares it as type 'AddStudentFormProps'
const AddStudentForm = ({addStudent} : AddStudentFormProps) => {
    //the state for all properties in formData is inferred
    const [formData, setFormData] = useState({
        firstName: "",
        lastName: "",
        email: ""
    });

    //this defines the event 'e' as a change event generated by a HTML input, because of this the properties associated with the input are accessible (e.g. target) and therefore the types of name and value can be found.
    const handleInputChanges = (e: React.ChangeEvent<HTMLInputElement>) => {
        const {name, value} = e.target;

        setFormData((prevFormData) => {
            return {
                ...prevFormData,
                [name]: value //uses computed property names 
            }
        });
    }

    //this defines the event 'e' as a form submission event coming from a form element, because of this the preventDefault method is is accessible.
    const handleSubmitStudentForm = (e: React.SubmitEvent<HTMLFormElement>) => {
        e.preventDefault;

        //collect form data values and submit as the addStudent function's argument
        addStudent({
            id: uuidv4(),
            firstName: formData.firstName,
            lastName: formData.lastName,
            email: formData.email
        });

        //reset form data fields
        setFormData({
            firstName: '',
            lastName: '',
            email: ''
        });
    }

    return (
        <form action="" onSubmit={handleSubmitStudentForm}>
            <input
                type="text"
                placeholder="e.g. John"
                name="firstName"
                value={formData.firstName}
                onChange={(e) => handleInputChanges(e)}
            />
            <input
                type="text"
                placeholder="e.g. Doe"
                name="lastName"
                value={formData.lastName}
                onChange={(e) => handleInputChanges(e)}
            />
            <input
                type="text"
                placeholder="e.g. JohnDoe@gmail.com"
                name="email"
                value={formData.email}
                onChange={(e) => handleInputChanges(e)}
            />
            <button type="submit">Submit</button>
        </form>
    );
}

export default AddStudentForm;